### ISSUE TITLE
There is a conflict between phoneticPunctuation And speechHistory

### ISSUE THREAD

**Issue by cary-rowen** [jscholes/nvda-speech-history#32]
Hi, this issue was first posted here:
https://nvda-addons.groups.io/g/nvda-addons/topic/there_is_a_conflict_between/93740359?p=,,,50,0,0,0::recentpostdate/sticky,,,50,2,0,93740359,previd%3D1663409231650427604,nextid%3D1660470770410941754&previd=1663409231650427604&nextid=1660470770410941754

Hi, James Scholes and tony,
Thank you for developing these add-ons, When I installed these two add-ons at the same time, I found that the function of speechHistory is completely disabled, and there is no response when performing gestures. Can you take a look?
Thanks

speechHistory: https://addons.nvda-project.org/addons/speech_history.zh_CN.html

phoneticPunctuation: https://addons.nvda-project.org/addons/phoneticPunctuation.zh_CN.html

**Comment by cary-rowen** [comment]
cc @mltony

**Comment by jscholes** [comment]
I have no idea if this is still an issue, but soon I hope to transition the add-on to an extension point rather than monkey-patching which should fix it.  I won't be actively testing any other add-on's interop with this one though, so while I hope that does fix things if they're still broken, I'm closing this particular issue as unplanned.
